# This file tells Netlify how to build and deploy your site.
[build]
  # This command is a placeholder to ensure Netlify runs a build step,
  # which is necessary for environment variable injection.
  command = "echo 'Netlify build triggered for variable injection'"
  # The 'publish' directory is the root of your repository, where index.html and other assets reside.
  publish = "."